debug: false
trace: false

logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] [%-5level] %class{36}.%M | %msg%n'
  level:
    de.ba: debug
    root: info

app:
  basepath:
  web:
    title: 'PushMFA-Simulator'
  env: 'dev'
  # Default client credentials for device client defined in keycloak
  clientId: ${APP_CLIENTID:push-device-client}
  clientSecret: ${APP_CLIENTSECRET:device-client-secret}
  # Flag to disable SSE e.g. for last testing purposes
  sseFlag: ${APP_SSEFLAG:enabled}
  # Default provider IDs for select options in the UI
  providerIds: ${APP_PROVIDERIDS:log,fcm,none}
  # url replacement for "localhost"
  localhostReplacement: ${APP_LOCALHOSTREPLACEMENT:}

server:
  port: 5000
  address: 0.0.0.0
  forward-headers-strategy: framework
  servlet:
    context-path: /mock

security:
  jwk:
    private-key-location: classpath:keys/rsa-jwk.json

spring:
  application:
    name: 'pushmfa-simulator'
    version: 'latest'
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: off
  jackson:
    mapper:
      accept-case-insensitive-properties: true
  thymeleaf:
    prefix: 'classpath:views/'
    cache: false
    suffix: .html
  web:
    resources:
      cache:
        period: 0
      static-locations: 'classpath:static'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
        add-additional-paths: true
  health:
    defaults:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
